name: socio_calcu
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: 4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
